services:
  providersmartapp:
    image: chroniccare/mccproviderv2
    container_name: mccproviderv2
    domainname: mccproviderv2
    network_mode: default
    environment:
      CLIENT_ID : ${CLIENT_ID}
    ports:
      - "80:80"
    restart: always
